spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db 
    username: postgres 
    password: postgres

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

server:
  port: ${SERVER_PORT:8082}

  logging:
  level:
    org.springframework.security: DEBUG