spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/account_db #${SPRING_DATASOURCE_URL}
    username: postgres #${SPRING_DATASOURCE_USERNAME}
    password: postgres #${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

server:
  port: ${SERVER_PORT:8081}